apiVersion: v1
kind: Service
metadata:
  name: gocachehub-service
  namespace: go
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: gocachehub