apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocachehub-deployment
  namespace: go
  labels:
    app: gocachehub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gocachehub
  template:
    metadata:
      labels:
        app: gocachehub
    spec:
      containers:
      - name: gocachehub
        image: registry.digitalocean.com/admdnlr/gocachehub:v0.29-45c19f8
        ports:
        - containerPort: 9080
      imagePullSecrets:
        - name: regcred