apiVersion: v1
kind: Service
metadata:
  name: gocachehub-service
  namespace: go
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    NodePort: 30008
    protocol: TCP
  selector:
    app: gocachehub